
services:
  apache:
    build: .
    container_name: apache-dev-php74
    ports:
      - "8081:80"
    volumes:
      - ./www:/www         # Solo montamos el código fuente, no el archivo de configuración
    restart: always
